package com.norrisjackson.jsnippets;

import org.springframework.beans.factory.ObjectProvider;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.info.BuildProperties;
import org.springframework.stereotype.Component;

/**
 * Exposes build metadata (application version and source revision) to the UI.
 *
 * <p>The version is sourced from the {@code META-INF/build-info.properties} generated by the
 * Spring Boot Maven plugin. The git commit is supplied at container build time via the
 * {@code APP_GIT_COMMIT} environment variable (see the Dockerfile / build-image.sh); when it is
 * not present (e.g. a local IDE run) it falls back to {@code unknown}.
 */
@Component
public class AppInfo {

    private final String version;
    private final String commit;

    public AppInfo(ObjectProvider<BuildProperties> buildProperties,
                   @Value("${app.git.commit:unknown}") String commit) {
        BuildProperties build = buildProperties.getIfAvailable();
        this.version = (build != null) ? build.getVersion() : "dev";
        this.commit = commit;
    }

    /**
     * @return the application version, e.g. {@code 1.0.6-SNAPSHOT}
     */
    public String getVersion() {
        return version;
    }

    /**
     * @return the abbreviated git commit the build was produced from, or {@code unknown}
     */
    public String getCommit() {
        return commit;
    }

    /**
     * @return a display string suitable for a tooltip, e.g. {@code v1.0.6-SNAPSHOT / abcdef123456}
     */
    public String getDisplay() {
        return "v" + version + " / " + commit;
    }
}
